#!/bin/sh

# Lint C++ files
cpplint --recursive --quiet src tests
if [ $? -eq 0 ] then
  echo "cpplint returned with no errors"
else
  exit $?
fi

# Lint Python files
find src tests -type f -name "*.py" | xargs pylint
if [ $? -ne 0 ] then
  exit $?
fi

# Build and test the project
cd build
if [ $? -ne 0 ] then
  res=$?
  echo "build folder not configured"
  exit $res
fi
make
if [ $? -ne 0 ] then
  exit $?
fi
./bin/tests.out
if [ $? -ne 0 ] then
  exit $?
fi

exit 0
