#!/bin/sh
set -e

echo "Linting C++ Files..."
api/venv/bin/cpplint --recursive --quiet ai/src ai/tests

echo "Linting Python Files..."
find api/src -type f -name "*.py" | xargs api/venv/bin/pylint

echo "Building..."
docker build -t fishbait-ai ./ai

echo "Testing..."
docker run --rm fishbait-ai /build/bin/tests.out

exit 0
