#!/bin/sh

echo "Linting C++ Files..."
cpplint --recursive --quiet src tests || { exit 1; }

echo "Linting Python Files..."
find src tests -type f -name "*.py" | xargs pylint || { exit 1; }

echo "Building..."
cmake --build build --config Debug || { exit 1; }

echo "Testing..."
cd build || { exit 1; }
./bin/tests.out || { exit 1; }

exit 0
