# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/marzukrashid/Desktop/pluribus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/marzukrashid/Desktop/pluribus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marzukrashid/Desktop/pluribus/CMakeFiles /Users/marzukrashid/Desktop/pluribus//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marzukrashid/Desktop/pluribus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.out

# Build rule for target.
main.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main.out
.PHONY : main.out

# fast build rule for target.
main.out/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/main.out.dir/build.make src/CMakeFiles/main.out.dir/build
.PHONY : main.out/fast

#=============================================================================
# Target rules for targets named poker

# Build rule for target.
poker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poker
.PHONY : poker

# fast build rule for target.
poker/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/poker.dir/build.make src/CMakeFiles/poker.dir/build
.PHONY : poker/fast

#=============================================================================
# Target rules for targets named omp_lib

# Build rule for target.
omp_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_lib
.PHONY : omp_lib

# fast build rule for target.
omp_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/omp/CMakeFiles/omp_lib.dir/build.make src/omp/CMakeFiles/omp_lib.dir/build
.PHONY : omp_lib/fast

#=============================================================================
# Target rules for targets named isomorphism_lib

# Build rule for target.
isomorphism_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 isomorphism_lib
.PHONY : isomorphism_lib

# fast build rule for target.
isomorphism_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/isomorphism/CMakeFiles/isomorphism_lib.dir/build.make src/isomorphism/CMakeFiles/isomorphism_lib.dir/build
.PHONY : isomorphism_lib/fast

#=============================================================================
# Target rules for targets named cpp_experiment.out

# Build rule for target.
cpp_experiment.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_experiment.out
.PHONY : cpp_experiment.out

# fast build rule for target.
cpp_experiment.out/fast:
	$(MAKE) $(MAKESILENT) -f src/abstraction/CMakeFiles/cpp_experiment.out.dir/build.make src/abstraction/CMakeFiles/cpp_experiment.out.dir/build
.PHONY : cpp_experiment.out/fast

#=============================================================================
# Target rules for targets named hand_evaluator

# Build rule for target.
hand_evaluator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hand_evaluator
.PHONY : hand_evaluator

# fast build rule for target.
hand_evaluator/fast:
	$(MAKE) $(MAKESILENT) -f src/abstraction/CMakeFiles/hand_evaluator.dir/build.make src/abstraction/CMakeFiles/hand_evaluator.dir/build
.PHONY : hand_evaluator/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cpp_experiment.out"
	@echo "... hand_evaluator"
	@echo "... isomorphism_lib"
	@echo "... main.out"
	@echo "... omp_lib"
	@echo "... poker"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

