// Copyright 2021 Marzuk Rashid

#include <vector>

#include "catch2/catch.hpp"
#include "blueprint/sequence_table.h"
#include "poker_engine/node.h"

TEST_CASE("6 players all in or fold", "[blueprint][sequence_table]") {
  std::vector<blueprint::Action> actions = {{poker_engine::Action::kFold},
                                            {poker_engine::Action::kAllIn}};
  poker_engine::Node<6> start_state;
  blueprint::SequenceTable<6> seq{actions, start_state};

  std::vector<uint32_t> correct = {1, 31, 2, 16, 3, 9, 4, 6, 0, 5, 0, 0, 7, 8,
                                   0, 0, 0, 0, 10, 13, 11, 12, 0, 0, 0, 0, 14,
                                   15, 0, 0, 0, 0, 17, 24, 18, 21, 19, 20, 0, 0,
                                   0, 0, 22, 23, 0, 0, 0, 0, 25, 28, 26, 27, 0,
                                   0, 0, 0, 29, 30, 0, 0, 0, 0, 32, 47, 33, 40,
                                   34, 37, 35, 36, 0, 0, 0, 0, 38, 39, 0, 0, 0,
                                   0, 41, 44, 42, 43, 0, 0, 0, 0, 45, 46, 0, 0,
                                   0, 0, 48, 55, 49, 52, 50, 51, 0, 0, 0, 0, 53,
                                   54, 0, 0, 0, 0, 56, 59, 57, 58, 0, 0, 0, 0,
                                   60, 61, 0, 0, 0, 0};
  REQUIRE(seq.States() == 62);
  REQUIRE(seq.Actions() == 2);
  for (size_t i = 0; i < seq.States(); ++i) {
    for (size_t j = 0; j < seq.Actions(); ++j) {
      REQUIRE(seq.Next(i, j) == correct[i * seq.Actions() + j]);
    }
  }
}  // TEST_CASE "6 players all in or fold"

TEST_CASE("3 player all in fold check pot bet", "[blueprint][sequence_table]") {
  std::vector<blueprint::Action> actions =
      {{poker_engine::Action::kFold},
       {poker_engine::Action::kAllIn},
       {poker_engine::Action::kCheckCall},
       {poker_engine::Action::kBet, 1.0, 1, poker_engine::Round::kPreFlop}};
  poker_engine::Node<3> start_state;
  blueprint::SequenceTable<3> seq{actions, start_state};

  std::vector<uint32_t> correct = {1, 59, 62, 344, 0, 2, 3, 31, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 4, 5, 17, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 6, 7, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 8, 9, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 10, 11,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 12,
      13, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      14, 15, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 16, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 18, 19, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 20, 21, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 22, 23, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 24, 25, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 26, 27,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 28,
      29, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      30, 0, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 32, 33,
      45, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 34, 35,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 36,
      37, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      38, 39, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 40, 41, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 42, 43, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 44, 0, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, 0, 46, 47, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 48, 49, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 50, 51, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 52, 53,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 54,
      55, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      56, 57, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 58, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 60, 61, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 63,
      91, 94, 204, seq.kIllegalId, 64, 65, 77, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 66, 67, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 68, 69, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 70, 71,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 72,
      73, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      74, 75, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 76, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 78, 79, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 80, 81, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 82, 83, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 84, 85,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 86,
      87, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      88, 89, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 90, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 92, 93, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 95, 98, 134, 96, 97, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 99, 102, seq.kIllegalId, 100, 101, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 103, 106, seq.kIllegalId,
      104, 105, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 107,
      110, seq.kIllegalId, 108, 109, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 111, 114, seq.kIllegalId, 112, 113, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 115, 118, seq.kIllegalId,
      116, 117, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 119,
      122, seq.kIllegalId, 120, 121, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 123, 126, seq.kIllegalId, 124, 125, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 127, 130, seq.kIllegalId,
      128, 129, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 131,
      0, seq.kIllegalId, 132, 133, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 135,
      149, 152, seq.kIllegalId, 0, 136, 137, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 138, 139, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 140, 141,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 142,
      143, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      144, 145, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 146, 147, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 148, 0, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 150, 151, seq.kIllegalId, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 153, 165, 168, seq.kIllegalId, seq.kIllegalId, 154, 155,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 156,
      157, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      158, 159, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 160, 161, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 162, 163, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 164, 0, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, 166, 167, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 169, 172, seq.kIllegalId,
      170, 171, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 173,
      176, seq.kIllegalId, 174, 175, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 177, 180, seq.kIllegalId, 178, 179, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 181, 184, seq.kIllegalId,
      182, 183, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      185, 188, seq.kIllegalId, 186, 187, seq.kIllegalId, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 189, 192, seq.kIllegalId, 190, 191,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 193, 196,
      seq.kIllegalId, 194, 195, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 197, 200, seq.kIllegalId, 198, 199, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 201, 0, seq.kIllegalId,
      202, 203, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 205, 219, 222, 274,
      0, 206, 207, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 208, 209, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 210, 211, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 212, 213, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 214, 215,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 216,
      217, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      218, 0, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 220, 221,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, 223, 235, 238, seq.kIllegalId,
      seq.kIllegalId, 224, 225, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 226, 227, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 228, 229, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 230, 231,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 232,
      233, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      234, 0, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 236, 237,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 239, 242,
      seq.kIllegalId, 240, 241, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 243, 246, seq.kIllegalId, 244, 245, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 247, 250, seq.kIllegalId,
      248, 249, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 251,
      254, seq.kIllegalId, 252, 253, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 255, 258, seq.kIllegalId, 256, 257, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 259, 262, seq.kIllegalId,
      260, 261, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      263, 266, seq.kIllegalId, 264, 265, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 267, 270, seq.kIllegalId, 268, 269, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 271, 0, seq.kIllegalId,
      272, 273, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 275, 289, 292,
      seq.kIllegalId, 0, 276, 277, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 278, 279, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 280, 281, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 282, 283,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 284,
      285, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      286, 287, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 288, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 290, 291, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 293,
      305, 308, seq.kIllegalId, seq.kIllegalId, 294, 295, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 296, 297, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 298, 299,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 300,
      301, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      302, 303, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 304, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 306, 307, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 309, 312, seq.kIllegalId, 310, 311, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 313, 316, seq.kIllegalId,
      314, 315, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 317,
      320, seq.kIllegalId, 318, 319, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 321, 324, seq.kIllegalId, 322, 323, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 325, 328, seq.kIllegalId,
      326, 327, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 329,
      332, seq.kIllegalId, 330, 331, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 333, 336, seq.kIllegalId, 334, 335, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 337, 340, seq.kIllegalId,
      338, 339, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 341,
      0, seq.kIllegalId, 342, 343, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 345,
      373, 376, 498, 0, 346, 347, 359, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 348, 349, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 350, 351, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 352, 353, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 354, 355,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 356,
      357, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      358, 0, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 360, 361,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 362,
      363, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      364, 365, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 366, 367, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 368, 369, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 370, 371, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 372, 0,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 374, 375,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, 377, 389, 392, 428, seq.kIllegalId,
      378, 379, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 380, 381, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 382, 383, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 384, 385, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 386, 387,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 388,
      0, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 390, 391,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 393, 396,
      seq.kIllegalId, 394, 395, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 397, 400, seq.kIllegalId, 398, 399, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 401, 404, seq.kIllegalId,
      402, 403, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 405,
      408, seq.kIllegalId, 406, 407, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 409, 412, seq.kIllegalId, 410, 411, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 413, 416, seq.kIllegalId,
      414, 415, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 417,
      420, seq.kIllegalId, 418, 419, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 421, 424, seq.kIllegalId, 422, 423, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 425, 0, seq.kIllegalId,
      426, 427, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 429, 443, 446,
      seq.kIllegalId, 0, 430, 431, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 432, 433, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 434, 435, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 436, 437,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 438,
      439, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      440, 441, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 442, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 444, 445, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 447,
      459, 462, seq.kIllegalId, seq.kIllegalId, 448, 449, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 450, 451, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 452, 453,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 454,
      455, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      456, 457, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 458, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 460, 461, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 463, 466, seq.kIllegalId, 464, 465, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 467, 470, seq.kIllegalId,
      468, 469, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 471,
      474, seq.kIllegalId, 472, 473, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 475, 478, seq.kIllegalId, 476, 477, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 479, 482, seq.kIllegalId,
      480, 481, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 483,
      486, seq.kIllegalId, 484, 485, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 487, 490, seq.kIllegalId, 488, 489, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 491, 494, seq.kIllegalId,
      492, 493, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 495,
      0, seq.kIllegalId, 496, 497, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 499,
      513, 516, 568, 0, 500, 501, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 502, 503, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 504, 505, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 506, 507,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 508,
      509, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      510, 511, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 512, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 514, 515, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 517,
      529, 532, seq.kIllegalId, seq.kIllegalId, 518, 519, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 520, 521, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 522, 523,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 524,
      525, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      526, 527, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 528, 0, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 530, 531, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 533, 536, seq.kIllegalId, 534, 535, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 537, 540, seq.kIllegalId,
      538, 539, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 541,
      544, seq.kIllegalId, 542, 543, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 545, 548, seq.kIllegalId, 546, 547, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 549, 552, seq.kIllegalId,
      550, 551, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 553,
      556, seq.kIllegalId, 554, 555, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 557, 560, seq.kIllegalId, 558, 559, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 561, 564, seq.kIllegalId,
      562, 563, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 565,
      0, seq.kIllegalId, 566, 567, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 569,
      583, 586, seq.kIllegalId, 0, 570, 571, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 572, 573, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 574, 575,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 576,
      577, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      578, 579, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 580, 581, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 582, 0, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 584, 585, seq.kIllegalId, seq.kIllegalId,
      0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 587, 599, 602, seq.kIllegalId, seq.kIllegalId, 588, 589,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 590,
      591, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId,
      592, 593, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 594, 595, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, seq.kIllegalId, 596, 597, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 598, 0, seq.kIllegalId, 0,
      0, seq.kIllegalId, seq.kIllegalId, 600, 601, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 603, 606, seq.kIllegalId,
      604, 605, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 607,
      610, seq.kIllegalId, 608, 609, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 611, 614, seq.kIllegalId, 612, 613, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 615, 618, seq.kIllegalId,
      616, 617, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 619,
      622, seq.kIllegalId, 620, 621, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 623, 626, seq.kIllegalId, 624, 625, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 627, 630, seq.kIllegalId,
      628, 629, seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, seq.kIllegalId, 631,
      634, seq.kIllegalId, 632, 633, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId,
      seq.kIllegalId, 635, 0, seq.kIllegalId, 636, 637, seq.kIllegalId,
      seq.kIllegalId, 0, 0, seq.kIllegalId, seq.kIllegalId, 0, 0,
      seq.kIllegalId, seq.kIllegalId};
  REQUIRE(seq.States() == 638);
  REQUIRE(seq.Actions() == 4);
  for (size_t i = 0; i < seq.States(); ++i) {
    for (size_t j = 0; j < seq.Actions(); ++j) {
      REQUIRE(seq.Next(i, j) == correct[i * seq.Actions() + j]);
    }
  }
}  // TEST_CASE "3 player all in fold check pot bet"
